### ISSUE TITLE
About 'Sequences' subsets

### ISSUE THREAD

**Issue by Viot-HUST** [zenseact/zod#12]
Hello! Thank you for your contribution. I'm very interested in this dataset.
According to the introduction, do 'Sequences' subsets have no night scenes?

**Comment by wljungbergh** [comment]
Hi. Thanks for your interest in our dataset.

The sequences have been captured during different times, the earliest one being at 5:42 am and the latest at 16.11 pm. While there are no sequences late at night, you should be able to find sequences that have low illumination early in the morning.

**Comment by wljungbergh** [comment]
Hi. Thanks for your interest in our dataset.

The sequences have been captured during different times, the earliest one being at 5:42 am and the latest at 16.11 pm. While there are no sequences late at night, you should be able to find sequences that have low illumination early in the morning.

**Comment by wljungbergh** [comment]
Please reopen this issue if you have any further questions.

**Comment by wljungbergh** [comment]
Please reopen this issue if you have any further questions.
