### ISSUE TITLE
Question regarding data capturing frequency

### ISSUE THREAD

**Issue by alchemz** [zenseact/zod#17]
Dear ZOD admins,

Could you help clarify if ZOD has been collected using constant frequency 10HZ, or it depends on driving speed and scenarios? Specifically, what is the data capturing frequency on urban and highway respectively.

Thanks!

**Comment by atonderski** [comment]
Hi,

ZOD has been collected using a roughly constant, sensor-dependent frequency.

For example, the lidar is always spinning at roughly 10Hz, independent of driving speed and scenario. We recommend using the exact time differences provided in the data, however, as it is not exactly 10Hz and this error will accumulate if aggregating many scans.
