### ISSUE TITLE
LiDAR Detections Front view

### ISSUE THREAD

**Issue by NithinDonepudi** [zenseact/zod#21]
Hello ZOD Developers! I noticed while visualizing the bounding boxes for the LiDAR that the annotations seem to be only from the front of the vehicle. Is there a way to access annotations from behind as well?

**Comment by atonderski** [comment]
Hi! Yes you are right, annotations are only released for the overlapping region that is visible in both the camera and lidar, corresponding to roughly to a 120 degree field-of-view. Unfortunately, we do not currently plan to release annotations for the remaining field of view.

**Comment by Petros626** [comment]
@NithinDonepudi, @atonderski  do you know the height of the lidar on the car? Can you provide meaningful values for the point cloud range?

`POINT_CLOUD_RANGE: [x_min, y_min, z_min, x_max, y_max, z_max]`
