### ISSUE TITLE
Accuracy of data with 'fog' labels. 

### ISSUE THREAD

**Issue by siddhantsom** [zenseact/zod#30]
My supervisor and I have been trying to work with the ZOD dataset for the purpose of weather detection. We were using the RGB data, and as labels we had decided to use the 'scraped-weather' parameter from the meta data json file, because it has values such as 'clear', 'rain', 'snow' etc, which can be used as class labels. One of the class labels is 'fog', however it is not clear as to how they are classified, because they easily come under some of the other labels such as 'cloudy', 'rain' and 'snow'. There is no clear indication of fog, at least in RGB. 
![fog](https://github.com/zenseact/zod/assets/62664753/e85683ef-b3bd-43cb-b5a7-5e693cbe2f1b)

![029193_golf_2021-01-20T11_27_50 115510Z](https://github.com/zenseact/zod/assets/62664753/81e90e91-137c-40e4-a5d2-a9c304d6f89f)
![030057_golf_2021-01-10T10_24_18 004076Z](https://github.com/zenseact/zod/assets/62664753/80af4e25-b5c3-480a-b30c-6f1e07c7e7bb)

![003520_oscar_2021-04-15T14_37_55 113569Z](https://github.com/zenseact/zod/assets/62664753/9f7d0124-490f-4e0d-953c-0a80ef2f2732)
![005790_oscar_2021-04-15T14_18_19 330970Z](https://github.com/zenseact/zod/assets/62664753/15c50503-929c-4069-9410-0d0739c0c760)

**Comment by wljungbergh** [comment]
Hi. 

As (somewhat) indicated by the name of the field, the data is _scraped_ from online resources in post-processing. This unfortunately leads to metadata that is not correct. This is a limitation but I hope that you can still make use of the dataset. 

However, if you are able to more accurately classify the weather of each frame (including fog etc.,), we would very much like to add it to the dataset. If you do so, please contact us either here or at opendataset@zenseact.com
