### ISSUE TITLE
YOLOV7 Pre-trained Weights

### ISSUE THREAD

**Issue by RPalmr** [zenseact/zod#34]
Are the YOLOV7 pre-trained weights available in the dropbox files, trained on just the 4 main classes ("Vehicle", "VulnerableVehicle", "Pedestrian", "Animal")? If so is it advised to then break these down into the subclasses listed in the anno/object.py by adding more classes to the existing pytorch model?

**Comment by wljungbergh** [comment]
Hi, 

The pretrained weights that are available on Dropbox were trained only with the super-classes shown in the paper (i.e., Vehicle", "VulnerableVehicle", "Pedestrian"). We have not yet defined any official benchmark (and therefore not the final classes to be used) for the dataset. This will be done in the future.

You are very welcome to train and publish the weights for a more granular class taxonomy.
