### ISSUE TITLE
No response about downloading

### ISSUE THREAD

**Issue by jiaxiaosong1002** [zenseact/zod#37]
Dear authors,

I have followed the instructions at https://zod.zenseact.com/download/ and write an email to request download links.  However, I do not receive any response after more than 10 days. I am not sure whether the email requesting system works nowadays.  Could you please give me some information? The email I use to request is jiaxiaosong@sjtu.edu.cn. 

Thanks!

**Comment by wljungbergh** [comment]
Hi, 

We apologize for the delay in your processing your request. It should have been processed now and you should have access to the dataset. Hope you find it useful.
