### ISSUE TITLE
Converting to Yolo Format

### ISSUE THREAD

**Issue by TheBigCodeman** [zenseact/zod#42]
I am new to coding, and looking to train a YoloV7/8 traffic sign and light detection and classification model. I noticed the blur and dnat images were raw and un-annotated and the annotations were in .json format. What is the best way to convert all to Yolo format please? Should this be done manually and the images be relabelled and exported using Roboflow, for example? This seems quite time consuming, so what is recommended for all the image annotations, maybe 10% and then use this to train the rest? Thank you and I apologise if I am missing the obvious.

**Comment by wljungbergh** [comment]
Hi, 

We have some utility scripts that might be helpful to you. First, you have `zod/cli/extract_tsr_patches.py` which can crop out all traffic signs in every image and place each of them in a folder with the name of the traffic sign as the folder name. This is the same as many other classification datasets (including ImageNet).

Second, you can use `zod/cli/generate_coco_json.py` to generate coco-style annotations for your detection pipeline. However, currently, this is done only for objects (cars, pedestrians, bicycles, etc.,), but it should be fairly easy to modify it to instead output the annotations for different traffic signs only.

Hope this gives you some inspiration on where to start.

**Comment by wljungbergh** [comment]
Feel free to open up this again if you have any questions.

**Comment by TheBigCodeman** [comment]
Hey,

I have encountered the issue 

`AssertionError: Project AnnotationProject.TRAFFIC_SIGNS not available.`

I have tried using another issues' resolution, which also stated that this is because 

> some annotations don't have traffic signs.

`try:
        traffic_signs: List[parser.TrafficSignAnnotation] = frame.get_annotation(
            constants.AnnotationProject.TRAFFIC_SIGNS
        )
except AssertionError:
        return []`

 which resulted in outputting an empty JSON file, which looks like
 
 `{"train": [], "val": []}`
 
 The code however, does successfully output all the images (both train & val), though it reaches 99995 out of 100000 - I believe this may be normal.
