### ISSUE TITLE
extract_tsr_patches.py bug

### ISSUE THREAD

**Issue by TheBigCodeman** [zenseact/zod#45]
Hey,

I have encountered the issue

`AssertionError: Project AnnotationProject.TRAFFIC_SIGNS not available.`

I have tried using another issues' resolution, which also stated that this is because

some annotations don't have traffic signs.

```
try:
        traffic_signs: List[parser.TrafficSignAnnotation] = frame.get_annotation(
            constants.AnnotationProject.TRAFFIC_SIGNS
        )
except AssertionError:
        return []
```

which resulted in outputting an empty JSON file, which looks like

`{"train": [], "val": []}`

The code however, does successfully output all the images (both train & val), though it reaches 99995 out of 100000 - I believe this may be normal. 

And how does the dataset want us to do TrafficSignal classification please?

**Comment by wljungbergh** [comment]
Hi, we have now fixed this file and also added an interface in the CLI ([see this commit](https://github.com/zenseact/zod/commit/94f02c5a003913aa849a40b8d9aa537741e60747)). You can now extract the patches by running the following code
```
zod generate tsr-patches --dataset-root <path-to-dataset> --output-dir "/tmp/zod-patches" --version mini
```

As for _TrafficSignal Classification_. We do not have any labels on what state the traffic signal is in (red, green yellow), hence we do not have the possibility to do classification.
