### ISSUE TITLE
No response about downloading

### ISSUE THREAD

**Issue by cppcute-pm** [zenseact/zod#46]
Dear authors,

I have followed the instructions at https://zod.zenseact.com/download/ and write an email to request download links. However, I do not receive any response after that. I am not sure whether the email requesting system works nowadays. Could you please give me some information? The email I use to request is 2233589@tongji.edu.cn.

Thanks!

**Comment by wljungbergh** [comment]
Hi, 

Thanks for reaching out. We very much apologize for the delay. You should have received a reply now with the downloading instructions.
