### ISSUE TITLE
zenseact open dataset download

### ISSUE THREAD

**Issue by creat112112** [zenseact/zod#57]
Dear Zenseact,

I have already sent you an email, but I have not received a response yet. I am looking forward to hearing from you.

I am interested in using the Zenseact Open Dataset (ZOD) for my research and I would like to request access to the dataset.
Please find the requested information below:

Email: liangyanyu0118@gmail.com

Intended use:
During the process of literature review and resource search, I came across the Zod dataset provided by your esteemed institution, which appears to be highly suitable for my current research needs. I believe that by utilizing the Zod dataset, I can conduct a more in-depth analysis of LiDAR perception models and contribute valuable insights and solutions to the field of autonomous driving.

I am looking forward to a positive response and am willing to provide any further information or documentation required. Thank you for considering my request, and I am hopeful for the opportunity to collaborate with you.

Best regards

**Comment by wljungbergh** [comment]
Hi, 

Sorry for the late reply and that we missed your email. You should have gotten access now. If not, please let us know!

**Comment by Petros626** [comment]
@creat112112 how many days for you? I still got not answer for the access.
