### ISSUE TITLE
zenseact dataset download #57

### ISSUE THREAD

**Issue by soyeollee** [zenseact/zod#58]
Hello.

A few days ago, I sent an email regarding get dataset, but I have not received a response yet.
I want to use this dataset for fine tuning AI Model. For detailed, please refer my email.

email: soyeol.lee.main@gmail.com (to opendataset@zenseact.com)
Intended use: AI model finetuning for AI competition 

In light of this, I will be carefully following the ZOD dataset's license (CC BY-SA) when using this data.

Best regards

**Comment by wljungbergh** [comment]
Hi, thank you for your interest in our dataset. 

Sorry for the slow reply on getting access. You should have received the necessary information now.

Good luck with the finetuning.
